Repository sofastack/sofa-jraft, pull requests merged in 2019-11, with the labels that each got.

#323 (fix) Declare rpcClient to be volatile, fix #319
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractBoltClientService.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: bug, cla:yes, size/M

#332 feat/minor change learners
  jraft-core/src/main/java/com/alipay/sofa/jraft/CliService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/ReplicatorGroup.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/conf/Configuration.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/conf/ConfigurationEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/CliServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorGroupImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LogEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v2/V2Decoder.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v2/V2Encoder.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/AddLearnersRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/GetPeersRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/RemoveLearnersRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/ResetLearnersRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/codec/v2/LogEntryV2CodecFactoryTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/AbstractCliRequestProcessorTest.java
Labels: cla:yes, size/L

#312 Impl learner for jraft, #8
  jraft-core/src/main/java/com/alipay/sofa/jraft/CliService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/ReplicatorGroup.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/conf/Configuration.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/conf/ConfigurationEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/CliServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorGroupImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorType.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LocalFileMetaOutter.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LocalStorageOutter.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LogEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/RaftOutter.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v1/LogEntryV1CodecFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v1/V1Decoder.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v1/V1Encoder.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v2/LogOutter.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v2/V2Decoder.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v2/V2Encoder.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/ReplicatorOptions.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/CliClientService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/CliRequests.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RaftRpcServerFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RpcRequests.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/AddLearnersRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/BoltCliClientService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/GetPeersRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/RemoveLearnersRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/ResetLearnersRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/RocksDBLogStorage.java
  jraft-core/src/main/resources/cli.proto
  jraft-core/src/main/resources/log.proto
  jraft-core/src/main/resources/raft.desc
  jraft-core/src/main/resources/raft.proto
  jraft-core/src/test/java/com/alipay/sofa/jraft/conf/ConfigurationEntryTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/conf/ConfigurationTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/CliServiceTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorGroupTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/TestCluster.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/codec/v2/LogEntryV2CodecFactoryTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/AbstractCliRequestProcessorTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/AddLearnersRequestProcessorTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/GetPeersRequestProcessorTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/RemoveLearnersRequestProcessorTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/ResetLearnersRequestProcessorTest.java
Labels: cla:yes, size/XXL

#336 minor fixes
  jraft-core/src/main/java/com/alipay/sofa/jraft/RaftGroupService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorGroupImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/RepeatedTimer.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/StorageOptionsFactory.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/chaos/AbstractChaosTest.java
Labels: cla:yes, size/M

#334 Priority-based semi-deterministic leader election.
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ElectionPriority.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/PeerId.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/NodeOptions.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/conf/ConfigurationEntryTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/conf/ConfigurationTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/TestCluster.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/PeerIdTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/test/TestUtils.java
Labels: cla:yes, size/XL

#343 (feat) Support readIndex from learner
  jraft-core/src/main/java/com/alipay/sofa/jraft/conf/ConfigurationEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: cla:yes, size/M

#352 [ISSUE#347]upgrade the com.fasterxml.jackson.core:jackson-databind to version 2.9.10.1.
  jraft-example/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
Labels: cla:yes, size/XS

#351 (feat) Remove multiple of 10ms for windows platform.
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/timer/HashedWheelTimer.java
Labels: cla:yes, size/M

#345 feat/priority_by_zongtanghu
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ElectionPriority.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/PeerId.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/NodeOptions.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/conf/ConfigurationEntryTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/conf/ConfigurationTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/TestCluster.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/PeerIdTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/test/TestUtils.java
Labels: cla:yes, size/XL

#356 Remove unused imports
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/timer/HashedWheelTimer.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: cla:yes, size/M

#357 fix elect priority
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorGroupImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorGroupTest.java
Labels: bug, cla:yes, size/M

#358 Feature/some changes
  .travis.yml
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/RaftOptions.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: cla:yes, size/L

#355 About NullPointerException in Recycles
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Recyclers.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/RecyclersTest.java
Labels: First-time contributor, cla:yes, size/M

#360 minor change
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/CliServiceTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/RecyclersTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/rhea/AbstractDistributedLockTest.java
Labels: cla:yes, size/M

#363 feat/release 1.3.0
  jraft-core/pom.xml
  jraft-core/src/main/java/com/alipay/sofa/jraft/Iterator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/ReadOnlyService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/ReadIndexStatus.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-example/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/M

#361 (fix) Iterator#setErrorAndRollback may break ReadIndex promise, #317
  jraft-core/pom.xml
  jraft-core/src/main/java/com/alipay/sofa/jraft/Iterator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/ReadOnlyService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/ReadIndexStatus.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/FSMCallerTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-example/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: bug, cla:yes, size/L
