Repository sofastack/sofa-jraft, pull requests merged in 2019-09, with the labels that each got.

#261 (feat) add log
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/NodeRequestProcessor.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/NodeRequestProcessorTest.java
Labels: cla:yes, size/S

#272 (feat) atomically move file method
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/io/ProtoBufFile.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
Labels: cla:yes, size/M

#271 (feat) code format
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LocalRaftMetaStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/io/ProtoBufFile.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshot.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotCopier.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotMetaTable.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotReader.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotWriter.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/remote/RemoteFileCopier.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Describer.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
Labels: cla:yes, size/L

#274 [ISSUE#273]The log class name in the AbstractBoltClientService Class can be modified to AbstractBoltClientService.
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractBoltClientService.java
Labels: cla:yes, size/XS

#280 (feat) revert default log storage to be RocksDBLogStorage
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/DefaultJRaftServiceFactory.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/TestJRaftServiceFactory.java
Labels: cla:yes, size/S

#277 (feat) code format
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
Labels: cla:yes, size/M

#281 (feat) security fix
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractBoltClientService.java
  jraft-example/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
Labels: bug, cla:yes, size/S
