Repository sofastack/sofa-jraft, pull requests merged in 2019-10, with the labels that each got.

#285 fix/state listener
  jraft-core/src/main/java/com/alipay/sofa/jraft/RaftGroupService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/Ballot.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/election/ElectionBootstrap.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/election/ElectionNode.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/election/ElectionOnlyStateMachine.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StateListenerContainer.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StoreEngine.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/DefaultRheaKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVStoreStateMachine.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/KVStateMachineTest.java
Labels: bug, cla:yes, size/L

#289 feat/checksum snapshot
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/AbstractKVStoreSnapshotFile.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MemoryKVStoreSnapshotFile.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksKVStoreSnapshotFile.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/util/Partitions.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/util/ZipUtil.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/benchmark/raw/SnapshotBenchmark.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/KVStoreAccessHelper.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/TestSnapshotReader.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/TestSnapshotWriter.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/memorydb/MemoryKVStoreTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/rocksdb/RocksKVStoreTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/util/ZipUtilTest.java
Labels: cla:yes, size/XL

#293 feat/avoid copy of checksum
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LogEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/CrcUtil.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/CrcUtilTest.java
Labels: size/M

#287 feat/async snapshot
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LogEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/CrcUtil.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/concurrent/AdjustableSemaphore.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/CrcUtilTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/concurrent/AdjustableSemaphoreTest.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StoreEngine.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StoreEngineHelper.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/options/RocksDBOptions.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/options/StoreEngineOptions.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/AbstractKVStoreSnapshotFile.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVStoreSnapshotFile.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVStoreStateMachine.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MemoryKVStoreSnapshotFile.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MemoryRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksKVStoreSnapshotFile.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/util/Partitions.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/util/ZipUtil.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/benchmark/raw/SnapshotBenchmark.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/KVStoreAccessHelper.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/TestSnapshotReader.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/TestSnapshotWriter.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/memorydb/MemoryKVStoreTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/rocksdb/RocksKVStoreTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/util/ZipUtilTest.java
Labels: cla:yes, size/XXL

#302 (feat) contains key api
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/DefaultRegionKVService.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/KVCommandProcessor.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/RegionKVService.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StoreEngineHelper.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/DefaultRheaKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/RheaKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/cmd/store/BaseRequest.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/cmd/store/ContainsKeyRequest.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/cmd/store/ContainsKeyResponse.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/BatchRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVOperation.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVStoreStateMachine.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MemoryRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MetricsKVClosureAdapter.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MetricsRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RaftRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/memorydb/MemoryKVStoreTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/rhea/AbstractRheaKVStoreTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/rocksdb/RocksKVStoreTest.java
Labels: cla:yes, size/L

#321 (fix) raft options copy
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/RaftOptions.java
Labels: bug, cla:yes, size/XS

#325 (fix) fix remove metric failed on replicator destroy
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorTest.java
Labels: bug, cla:yes, size/S

#322 (feat) add current leader id to node describer
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
Labels: cla:yes, size/XS

#326 (fix) improve check null with rpcClient
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractBoltClientService.java
Labels: bug, cla:yes, size/S
