Repository sofastack/sofa-jraft, pull requests merged in 2019-12, with the labels that each got.

#366 (fix) AssertError is an error not exception
  jraft-core/src/main/java/com/alipay/sofa/jraft/closure/ReadIndexClosure.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/BoltRaftClientServiceTest.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StoreEngine.java
Labels: bug, cla:yes, size/M

#368 (feat)Add jepsen verification test for rheakv.
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-test/config/server.properties
  jraft-rheakv/rheakv-test/pom.xml
  jraft-rheakv/rheakv-test/src/main/java/com/alipay/sofa/jraft/rhea/test/atomic/client/AtomicClient.java
  jraft-rheakv/rheakv-test/src/main/java/com/alipay/sofa/jraft/rhea/test/atomic/client/AtomicClientTest.java
  jraft-rheakv/rheakv-test/src/main/java/com/alipay/sofa/jraft/rhea/test/atomic/command/BaseRequestCommand.java
  jraft-rheakv/rheakv-test/src/main/java/com/alipay/sofa/jraft/rhea/test/atomic/server/AtomicServer.java
  jraft-rheakv/rheakv-test/src/main/java/com/alipay/sofa/jraft/rhea/test/atomic/server/processor/BaseAsyncUserProcessor.java
  jraft-rheakv/rheakv-test/src/main/resources/log4j2.xml
Labels: cla:yes, enhancement, size/L

#365 (feat)Snapshot improve.
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/NodeOptions.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/SnapshotExecutorTest.java
Labels: cla:yes, size/M

#371 Feature snapshot improve
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java
Labels: cla:yes, size/S

#370 (fix): first snapshot is random
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: bug, cla:yes, size/M

#373 Improve first snapshot time
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: cla:yes, size/S

#375 Limit NodeManager cannot be new
  jraft-core/src/main/java/com/alipay/sofa/jraft/NodeManager.java
Labels: First-time contributor, cla:no, size/XS

#376 (feat) Improve readme
  README.md
  README_zh_CN.md
Labels: cla:yes, size/XS

#382 (feat) Upgrade sofabolt version
  jraft-core/src/main/java/com/alipay/sofa/jraft/RaftGroupService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RaftRpcServerFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractBoltClientService.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StoreEngine.java
  pom.xml
Labels: cla:yes, size/S

#385 (fix) Forgot to check learner replicator.
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorGroupImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: bug, cla:yes, size/M
