Repository sofastack/sofa-jraft, pull requests merged in 2019-08, with the labels that each got.

#223 (fix) upgrade jackson-databind (vulnerabilities found)
  jraft-example/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
Labels: cla:yes, size/XS

#227 (fix) fsync when download snapshot
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/remote/RemoteFileCopier.java
Labels: bug, cla:yes, question, size/XS

#232 [ISSUE#231]Remove the redundanct codes for RepeatedTimer Class.
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/RepeatedTimer.java
Labels: cla:no, size/XS

#233 (fix) Chinese to English
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/chaos/AbstractChaosTest.java
  pom.xml
Labels: cla:yes, size/XS

#238 (fix) forwards compatibility
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/DefaultRheaKVRpcService.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVOperation.java
  pom.xml
Labels: bug, cla:yes, size/S

#240 [ISSUE#239]Modify and polish the LogManagerTest unit test.
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/impl/LogManagerTest.java
Labels: cla:yes, size/XS

#243 (feat) release-1.2.6
  jraft-core/pom.xml
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Bits.java
  jraft-example/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S

#242 [ISSUE#241]Optimize ReplicatorOptions class to implement Copiable interface.
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorGroupImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/ReplicatorOptions.java
Labels: cla:yes, size/S

#249 [ISSUE#246]Implement for ReplicatorGroupTest Unit Class.
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorGroupTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorTest.java
Labels: cla:yes, size/L

#248 remove duplicate option set
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorGroupImpl.java
Labels: First-time contributor, cla:no, size/XS

#250 (fix) refactor unit test
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorGroupTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorTest.java
Labels: cla:yes, size/XL

#251 (fix) typo
  jraft-core/src/main/java/com/alipay/sofa/jraft/RaftServiceFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/closure/ReadIndexClosure.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/closure/SaveSnapshotClosure.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/closure/SynchronizedClosure.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/conf/ConfigurationManager.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/CliServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/IteratorWrapper.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/StateMachineAdapter.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/TimerManager.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/LogManager.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/LogStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/RaftMetaStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/SnapshotStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/SnapshotThrottle.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/Snapshot.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotWriter.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/ThroughputSnapshotThrottle.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/impl/LogManagerTest.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVStoreClosure.java
Labels: cla:yes, size/L

#253 README document links
  README.md
  README_zh_CN.md
Labels: cla:yes, size/S

#255 (fix) ISSUE[254]
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
Labels: bug, cla:yes, size/S

#260 minor fix for ThreadId
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/ThreadId.java
Labels: cla:yes, size/S

#256 Implement ReplicatorStateListener for Replicator consecutiveErrorTimes enhancement
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorGroupTest.java
Labels: cla:yes, size/L

#258 (feat) Enhancement with RepeatedTimer by HashedWheelTimer
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/RepeatedTimer.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/timer/HashedWheelTimer.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/timer/Timer.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/timer/TimerTask.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/RepeatedTimerTest.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/pd/HeartbeatSender.java
Labels: cla:yes, size/L
