Repository sofastack/sofa-jraft, pull requests merged in 2020-05, with the labels that each got.

#425 [fix] remove rpc address parser
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRaftRpcFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRpcClient.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/ClientServiceConnectionEventProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/JRaftRpcAddressParser.java
Labels: bug, cla:yes, size/L

#452 fix: MarshallerHelper.Map is not thread safety
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/MarshallerHelper.java
Labels: bug, cla:yes, size/XS

#458 (fix#411).TestLeaderStopAndReElectWithPriority unittest run failure.
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: bug, cla:yes, size/S
