Repository sofastack/sofa-jraft, pull requests merged in 2020-07, with the labels that each got.

#477 new bits util
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Bits.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/HeapByteBufUtil.java
  pom.xml
Labels: cla:yes, size/L

#482 Still use joint consensus when only one peer changed
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: cla:yes, size/S

#481 (fix) Flush output stream before calling fd.sync, #480
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/io/ProtoBufFile.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: bug, cla:yes, size/M

#490 do not allow write snapshot file outside of parent dir
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotCopier.java
Labels: cla:yes, size/S

#489 some fix/improve
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/ReplicatorGroup.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/RouteTable.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/closure/ReadIndexClosure.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReplicatorGroupImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/Checksum.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/ClientService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RpcClient.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RpcRequestClosure.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RpcRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractClientService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRpcClient.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/DefaultRaftClientService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/RocksDBLogStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/concurrent/LongHeldDetectingReadWriteLock.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/concurrent/LongHeldDetectingReadWriteLockTest.java
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcClient.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/RegionEngine.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/RequestProcessClosure.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StoreEngine.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/DefaultRheaKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/errors/InvalidRegionMembershipException.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/errors/InvalidRegionVersionException.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVClosureAdapter.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MetricsKVClosureAdapter.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RaftRawKVStore.java
  pom.xml
Labels: bug, cla:yes, size/XL
