Repository sofastack/sofa-jraft, pull requests merged in 2020-01, with the labels that each got.

#387 (fix):log args do not match
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
Labels: First-time contributor, bug, cla:no, size/XS

#388 Enable RocksDB force_consistency_checks = true
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/StorageOptionsFactory.java
Labels: cla:yes, size/XS

#394 solve PeerId cached toString result incorrect problem. Fixes gh-393
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/PeerId.java
Labels: First-time contributor, cla:no, size/XS
