Repository sofastack/sofa-jraft, pull requests merged in 2020-06, with the labels that each got.

#463 fix IndexOutOfBoundsException
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Recyclers.java
Labels: bug, cla:yes, size/S

#462 Some corner cases fixes
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RpcUtils.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractClientService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/remote/CopySession.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/impl/LogManagerTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/test/TestUtils.java
Labels: cla:yes, size/L

#465 Fix/some fix
  jraft-core/src/main/java/com/alipay/sofa/jraft/JRaftUtils.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/closure/ReadIndexClosure.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/SegmentList.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/timer/DefaultRaftTimerFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/timer/RaftTimerFactory.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: cla:yes, size/L

#467 release 1.3.2
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S

#470 Solve the potential security risk issue of jackson-databind.
  jraft-example/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
Labels: cla:yes, size/S
