Repository sofastack/sofa-jraft, pull requests merged in 2020-10, with the labels that each got.

#513 Fix/error response on future
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractClientService.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/AbstractClientServiceTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/AbstractClientServiceTest.java
Labels: bug, cla:yes, size/M

#519 fix openjdk benchmark no work (#518)
  jraft-example/bin/client_benchmark_start.sh
  jraft-example/bin/server_benchmark_start.sh
Labels: First-time contributor, bug, cla:yes, size/XS

#527 fix #526
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/PeerId.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/UtilsTest.java
Labels: First-time contributor, bug, cla:yes, size/L

#523 (fix) revisiting segment log storage and fix some corner cases
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/AbortFile.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/RocksDBSegmentLogStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/SegmentFile.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/CliServiceTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/impl/BaseLogStorageTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/impl/RocksDBSegmentLogStorageTest.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/priorityelection/PriorityElectionNode.java
Labels: bug, cla:yes, size/XL
