Repository sofastack/sofa-jraft, pull requests merged in 2020-04, with the labels that each got.

#413 feat/never discard the callback task
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRpcClient.java
Labels: cla:yes, size/M

#415 feat/upgrade jackson
  jraft-example/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
Labels: cla:yes, size/XS

#421 [release]1.3.1
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S

#432 (fix)Convert Ehinese comments to English comments.
  jraft-test/src/main/java/com/alipay/sofa/jraft/test/atomic/server/AtomicRangeGroup.java
  jraft-test/src/main/java/com/alipay/sofa/jraft/test/atomic/server/AtomicSnapshotFile.java
Labels: bug, cla:yes, size/M

#429 minor change for 'reverse scan' cr
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/DefaultRegionKVService.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/DefaultRheaKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/BaseRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MemoryRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RaftRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java
Labels: cla:yes, size/M

#427 Raft GRPC implement for RPC factory
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRaftRpcFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRpcClient.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/JRaftRpcAddressParser.java
  jraft-example/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcClient.java
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcRaftRpcFactory.java
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcServer.java
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/ObjectMarshaller.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/RouteTableTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/StatusTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/BallotBoxTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/CliServiceTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/ExpectClosure.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/FSMCallerTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/IteratorImplTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/IteratorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/MockClosure.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/MockStateMachine.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/ReadOnlyServiceTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/ReplicatorGroupTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/ReplicatorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/TestCluster.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/TestJRaftServiceFactory.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/core/V1JRaftServiceFactory.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/AbstractClientServiceTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/AppendEntriesBenchmark.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/ProtobufMsgFactoryTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/ProtobufSerializerTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/RpcResponseFactoryTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/FutureTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/PingRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/AbstractCliRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/AddLearnersRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/AddPeerRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/BaseCliRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/ChangePeersRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/GetPeersRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/RemoveLearnersRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/RemovePeerRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/ResetLearnersRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/ResetPeersRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/SnapshotRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/cli/TransferLeadershipRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/AppendEntriesRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/BaseNodeRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/DefaultRaftClientServiceTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/InstallSnapshotRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/NodeRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/PreVoteRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/ReadIndexRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/RequestVoteRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/core/TimeoutNowRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/test/MockAsyncContext.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/test/TestUtils.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/google/protobuf/ZeroByteStringHelperTest.java
  jraft-extension/rpc-grpc-impl/src/test/resources/log4j2.xml
  pom.xml
Labels: cla:yes, size/XXL
