Repository sofastack/sofa-jraft, pull requests merged in 2020-03, with the labels that each got.

#403 feat/joinable-task
  jraft-core/src/main/java/com/alipay/sofa/jraft/FSMCaller.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/Status.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/closure/JoinableClosure.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/Task.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: cla:yes, size/L

#408 Reset timer instead of `start()` when stepDown
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/RepeatedTimer.java
Labels: cla:yes, question, size/S

#409 (feat) Set segment file to be read-only after write and sync
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/RocksDBLogStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/RocksDBSegmentLogStorage.java
Labels: cla:yes, size/S
