Repository sofastack/sofa-jraft, pull requests merged in 2020-09, with the labels that each got.

#505 let the failed closure ran in callback executor
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RpcUtils.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractClientService.java
Labels: cla:yes, size/M

#504 reset connect backoff timer
  jraft-core/pom.xml
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcClient.java
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/M

#511 Feature/2020.09.22 changes
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/AppendEntriesRequestProcessor.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorGroupTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/impl/LogManagerTest.java
Labels: cla:yes, size/L

#510 [improve] ignore PreVoteRequest when not in conf
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/chaos/ChaosTestCluster.java
Labels: cla:yes, question, size/S
