Repository sofastack/sofa-jraft, pull requests merged in 2021-02, with the labels that each got.

#553 (fix) NodeImpl#describe don't print snapshotExecutor when it's null
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
Labels: bug, cla:yes, question, size/XS

#555 ci with github actions
  .github/workflows/build.yml
  .travis.yml
  README.md
  README_zh_CN.md
Labels: cla:yes, size/M

#554 fix some dependabot alerts
  jraft-example/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  pom.xml
Labels: bug, cla:yes, size/XS
