Repository sofastack/sofa-jraft, pull requests merged in 2021-12, with the labels that each got.

#727 1.3.9
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S

#729 update Node#changePeers comment
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
Labels: size/XS, cla:no, First-time contributor

#739 Export api of getLastCommittedIndex and getLastAppliedIndex.
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
Labels: cla:yes, size/S

#742 Log4j upgrade
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  pom.xml
Labels: cla:yes, size/S

#745 (fix) use atomic move to avoid file corruption
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotStorage.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/zip/ParallelZipStrategy.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/util/ZipUtil.java
Labels: bug, cla:yes, cla:no

#749 log4j upgrade
  pom.xml
Labels: cla:yes, size/XS

#738 Support a config to make read index read failfast.
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/ReadIndexStatus.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/RaftOptions.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReadOnlyServiceTest.java
Labels: cla:yes, size/M
