Repository sofastack/sofa-jraft, pull requests merged in 2021-11, with the labels that each got.

#708 io error logging
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LocalRaftMetaStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotReader.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotWriter.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/remote/CopySession.java
Labels: cla:yes, size/S

#714 typo
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/election/ElectionBootstrap.java
Labels: size/XS, cla:no, First-time contributor

#713 (fix) Potential blocking risk for thread calling JoinableClosure#run(status)
  jraft-core/src/main/java/com/alipay/sofa/jraft/closure/JoinableClosure.java
Labels: bug, cla:yes, size/XS, First-time contributor

#711 Format code in CounterStateMachine.
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/CounterStateMachine.java
Labels: cla:no, First-time contributor, size/M

#719 (fix) typo
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/CounterClient.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/CounterServer.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/priorityelection/PriorityElectionBootstrap.java
Labels: bug, cla:yes, size/XS, First-time contributor

#706 Rre check connection before send install snapshot request
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
Labels: cla:yes, size/XS

#690 fix: grpc conn refresh
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/ConnectionRefreshTest.java
  jraft-core/src/test/resources/log4j2.xml
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcClient.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/ConnectionRefreshTest.java
Labels: bug, cla:yes, size/L

#722 (fix) Call NodeImpl#join asynchronously after shutting down node, #71…
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
Labels: bug, cla:yes, size/M
