Repository sofastack/sofa-jraft, pull requests merged in 2021-05, with the labels that each got.

#574 [ISSUE #573] Fix the NPE in ElectionBootstrap
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/election/ElectionBootstrap.java
Labels: First-time contributor, bug, cla:yes, size/XS

#585 fix MetadataRpcClient#getClusterInfo returns null
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/cmd/pd/GetClusterInfoResponse.java
  jraft-rheakv/rheakv-pd/src/main/java/com/alipay/sofa/jraft/rhea/DefaultPlacementDriverService.java
Labels: First-time contributor, bug, cla:no, size/S

#580 upgrade the version of common-io
  pom.xml
Labels: cla:yes, size/XS

#586 fail-fast on connection fail
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/core/DefaultRaftClientService.java
Labels: cla:yes, size/M

#587 Fix BoltRpcClient checkConnection createIfAbsent param is not use
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRpcClient.java
Labels: bug, cla:yes, size/XS

#591 Update README.md
  README.md
Labels: cla:yes, size/XS

#593 Revert "Update README.md"
  README.md
Labels: cla:yes, size/XS

#595 Add community and known users into README
  README.md
  README_zh_CN.md
Labels: cla:yes, size/L
