Repository sofastack/sofa-jraft, pull requests merged in 2021-04, with the labels that each got.

#563 (feat) LogEntry's data should not be null, close #562
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LogEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/Task.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/LogEntryTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/codec/BaseLogEntryCodecFactoryTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/codec/v2/LogEntryV2CodecFactoryTest.java
Labels: cla:yes, size/M

#566 Memory optimize
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVClosureAdapter.java
Labels: First-time contributor, cla:yes, size/S

#564 Grpc max message size support config by user.
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcClient.java
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcRaftRpcFactory.java
Labels: First-time contributor, cla:yes, size/S

#561 Clear segments.
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MemoryRawKVStore.java
Labels: First-time contributor, cla:yes, size/XS

#567 release 1.3.6
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S

#570 Fix some log format problem.
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/SignalHelper.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/internal/UnsafeUtil.java
  jraft-extension/rpc-grpc-impl/src/main/java/com/alipay/sofa/jraft/rpc/impl/GrpcServer.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/util/pipeline/future/DefaultPipelineFuture.java
Labels: bug, cla:yes, size/S
