Repository sofastack/sofa-jraft, pull requests merged in 2021-06, with the labels that each got.

#602 Node interface add api, get node state.
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
Labels: cla:yes, size/S

#601 Use common static final file name when snapshotFileSave and snapshotFileLoad
  jraft-core/src/main/java/com/alipay/sofa/jraft/RaftGroupService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/LogExceptionHandler.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MemoryRawKVStore.java
Labels: cla:yes, question, size/M

#608 Modify the comment of getRemoteAddress in RpcContext
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RpcContext.java
Labels: First-time contributor, cla:no, size/XS

#609 Make checksumPeers more general
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/Checksum.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LogEntry.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/LogExceptionHandler.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/SegmentList.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/StorageOptionsFactory.java
Labels: cla:yes, size/M

#606 fix can't retry InstallSnapshot problem( #605 )
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/SnapshotExecutorTest.java
Labels: First-time contributor, bug, cla:yes, question, size/L

#616 add putIfAbsent method for InvokeContext
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/InvokeContext.java
Labels: cla:yes, size/XS

#621 add recycling logic for com.alipay.sofa.jraft.storage.snapshot.remote.CopySession#destBuf
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/remote/CopySession.java
Labels: cla:yes, size/XS

#628 Move the unmap function of the SegmentFile to Utils
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/SegmentFile.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
Labels: cla:yes, size/M

#625 Patch #609
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/Checksum.java
Labels: cla:yes, size/XS

#619 Fix memory leak.
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/LogExceptionHandler.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/DefaultRheaKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVClosureAdapter.java
Labels: bug, cla:yes, size/M
