Repository sofastack/sofa-jraft, pull requests merged in 2021-07, with the labels that each got.

#629 Memory optimize at log manager.
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/util/concurrent/disruptor/MessageEvent.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/util/concurrent/disruptor/TaskHandler.java
Labels: cla:yes, size/M

#598 feature: add learner to follower realize
  jraft-core/src/main/java/com/alipay/sofa/jraft/CliService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/CliServiceImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/CliServiceTest.java
Labels: First-time contributor, cla:yes, size/M

#635 Fix appendEntriesCounter to count the number of additional logs
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
Labels: bug, cla:yes, size/XS

#636 (fix) sun.nio.ch.DirectBuffer compile error in latest jdk, #633
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/SegmentFile.java
Labels: bug, cla:yes, size/M

#641 The replicator metrics data add probeCounter, ut need suit it.
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorTest.java
Labels: cla:yes, size/XS

#649 fix deadlocks between the segment producers and consumers
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/RocksDBSegmentLogStorage.java
Labels: bug, cla:yes, size/S

#643 Fix replicate-inflights-count metric didn't remove when replicator destroy
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
Labels: bug, cla:yes, question, size/S

#638 Fix threadId npe problem at com/alipay/sofa/jraft/core/Replicator.java:815
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
Labels: bug, cla:yes, size/M

#650 (fix) replicator test failure
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReplicatorTest.java
Labels: bug, cla:yes, size/XS
