Repository sofastack/sofa-jraft, pull requests merged in 2021-08, with the labels that each got.

#656 Use pipeline.fireOutbound to propagate outbound events.
  jraft-rheakv/rheakv-pd/src/main/java/com/alipay/sofa/jraft/rhea/pipeline/handler/PlacementDriverTailHandler.java
Labels: cla:yes, size/XS

#651 Transfer a method sendProbeRequest.
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
Labels: cla:yes, size/S

#661 Modify the Chinese comments in Sequence to English
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/Sequence.java
Labels: cla:yes, size/XS

#652 refresh configuration for membership change
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/pd/AbstractPlacementDriverClient.java
Labels: cla:yes, size/S

#659 1.3.8
  .github/workflows/build.yml
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/M

#666 fix #664 possible race in ThreadId.setError method
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/ThreadId.java
Labels: bug, cla:yes, First-time contributor, size/S
