Repository sofastack/sofa-jraft, pull requests merged in 2022-03, with the labels that each got.

#761 fix the issue #759: ParallelCompress cannot be used even though the c…
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/zip/ParallelZipStrategy.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/zip/ZipStrategyManager.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/zip/ZipStrategyManagerTest.java
Labels: bug, cla:yes, First-time contributor, size/M

#775 (fix) ClassCastException in SnapshotExecutorImpl, #728
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java
Labels: bug, cla:yes, size/XS

#783 (fix) refactor ThreadId and fix #781
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/RocksDBLogStorage.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/ThreadId.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/ThreadIdTest.java
Labels: bug, cla:yes, size/L

#790 Feature/fix node test
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ExpectClosure.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/MockStateMachine.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: bug, cla:yes, size/M

#791 1.3.10
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S

#797 fix the log of method AddNewLearners(#779)
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
Labels: bug, cla:yes, size/XS

#798 Follower ignore read operation
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVOperation.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVStoreStateMachine.java
Labels: cla:yes, size/S

#806 (fix) key not deleted in truncatePrefix
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/RocksDBLogStorage.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/impl/BaseLogStorageTest.java
Labels: bug, cla:yes, size/M

#807 1.3.10.bugfix
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S
