Repository sofastack/sofa-jraft, pull requests merged in 2022-02, with the labels that each got.

#763 Fix typo
  jraft-core/src/main/java/com/alipay/sofa/jraft/JRaftServiceFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/ReplicatorGroup.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/ThreadId.java
Labels: bug, cla:yes, size/XS, First-time contributor

#762 (feat) Adds sliceData and getReadOnlyData methods to LogEntry, #755
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/LogEntry.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/LogEntryTest.java
Labels: cla:yes, size/M

#760 Counter demo support grpc.
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/CounterClient.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/CounterClosure.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/CounterServer.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/rpc/CounterGrpcHelper.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/rpc/CounterOutter.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/rpc/GetValueRequest.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/rpc/GetValueRequestProcessor.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/rpc/IncrementAndGetRequest.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/rpc/IncrementAndGetRequestProcessor.java
  jraft-example/src/main/java/com/alipay/sofa/jraft/example/counter/rpc/ValueResponse.java
  jraft-example/src/main/resources/counter.proto
Labels: cla:yes, size/XXL

#764 Feature/backpressure
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/ReadOnlyServiceImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/error/OverloadException.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/ApplyTaskMode.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/NodeOptions.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/LogManager.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/ReadOnlyServiceTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/impl/LogManagerTest.java
Labels: cla:yes, size/L

#769 (feat) Use deleteFilesInRange/compactRange to replace deleteRange in …
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/RocksDBLogStorage.java
Labels: cla:yes, size/M
