Repository sofastack/sofa-jraft, pull requests merged in 2022-06, with the labels that each got.

#846 fix: waitId may be overflow in long running service
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/impl/LogManagerImpl.java
Labels: bug, cla:yes, size/XS

#848 add invite link for slack
  README.md
  README_zh_CN.md
Labels: cla:yes, size/XS

#849 1.3.11
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/bdb-log-storage-impl/pom.xml
  jraft-extension/java-log-storage-impl/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S
