Repository sofastack/sofa-jraft, pull requests merged in 2022-04, with the labels that each got.

#812 fix connect bug
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/AbstractClientService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRaftRpcFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/BoltRpcClient.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/rpc/ExtSerializerSupports.java
Labels: bug, cla:yes, size/M

#816 Fix executeApplyingTasks maybe npx
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
Labels: bug, size/XS, cla:no, First-time contributor

#818 1.3.10.bugfix_2
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S

#752 实现基于BDB的日志存储
  jraft-extension/bdb-log-storage-impl/pom.xml
  jraft-extension/bdb-log-storage-impl/src/main/java/com/alipay/sofa/jraft/core/BDBLogStorageJRaftServiceFactory.java
  jraft-extension/bdb-log-storage-impl/src/main/java/com/alipay/sofa/jraft/storage/impl/BDBLogStorage.java
  jraft-extension/bdb-log-storage-impl/src/main/resources/META-INF/services/com.alipay.sofa.jraft.JRaftServiceFactory
  jraft-extension/bdb-log-storage-impl/src/test/java/com/alipay/sofa/jraft/storage/BaseStorageTest.java
  jraft-extension/bdb-log-storage-impl/src/test/java/com/alipay/sofa/jraft/storage/impl/BDBLogStorageTest.java
  jraft-extension/bdb-log-storage-impl/src/test/java/com/alipay/sofa/jraft/storage/impl/BaseLogStorageTest.java
  jraft-extension/bdb-log-storage-impl/src/test/java/com/alipay/sofa/jraft/test/TestUtils.java
  jraft-extension/pom.xml
Labels: cla:yes, First-time contributor, size/XXL

#817 RouteTable refresh configuration add learner list
  jraft-core/src/main/java/com/alipay/sofa/jraft/RouteTable.java
Labels: cla:yes, size/XS, First-time contributor

#772 optimize: support jdk9+ compile code
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/Replicator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/UserLog.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/codec/v1/V1Decoder.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/FileService.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/log/SegmentFile.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/SnapshotFileReader.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/remote/CopySession.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/BufferUtils.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/ByteBufferCollector.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/CrcUtil.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/Utils.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/internal/UnsafeUtf8Util.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/LogEntryTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/AppendEntriesBenchmark.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/io/LocalFileReaderTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/snapshot/local/SnapshotFileReaderTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/CrcUtilTest.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/serialization/impl/protostuff/io/NioBufInput.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/serialization/impl/protostuff/io/NioBufOutput.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/serialization/impl/protostuff/io/UnsafeNioBufInput.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/serialization/impl/protostuff/io/UnsafeNioBufOutput.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/serialization/SerializerTest.java
  jraft-test/src/main/java/com/alipay/sofa/jraft/test/atomic/server/processor/BaseAsyncUserProcessor.java
Labels: cla:yes, size/L

#811 fixing typos
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/cli/TransferLeaderRequestProcessor.java
Labels: cla:yes
