Repository sofastack/sofa-jraft, pull requests merged in 2022-11, with the labels that each got.

#896 Upgrade rocksdb version to 7.7.3
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java
  pom.xml
Labels: cla:yes, size/M

#904 upgrade grpc to 1.50.2
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-extension/rpc-grpc-impl/src/main/java/io/grpc/netty/shaded/io/grpc/netty/NettyConnectionHelper.java
Labels: cla:yes, cla:no, size/S

#909 fix: contains_key bugfix
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/TestUtil.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/rocksdb/RocksKVStoreTest.java
Labels: bug, cla:yes, size/M
