Repository sofastack/sofa-jraft, pull requests merged in 2022-09, with the labels that each got.

#871 normalize copyright template
  LICENSE
Labels: cla:yes, size/XS

#878 Bug fix: add exec-maven-plugin version
  jraft-example/pom.xml
Labels: bug, size/XS, cla:no, First-time contributor

#880 feat: add methods to Node for getting last log indexes
  jraft-core/src/main/java/com/alipay/sofa/jraft/FSMCaller.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/Node.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/FSMCallerImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/FSMCallerTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
Labels: cla:yes, size/M
