Repository sofastack/sofa-jraft, pull requests merged in 2023-04, with the labels that each got.

#953 release: 1.3.13.beta
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/bdb-log-storage-impl/pom.xml
  jraft-extension/java-log-storage-impl/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/S

#961 Fix CVE dependency issue
  jraft-example/pom.xml
Labels: bug, size/XS, cla:no, First-time contributor

#963 optimize: null are allowed for expect or update value
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/client/DefaultRheaKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/MemoryRawKVStore.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/RocksRawKVStore.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/memorydb/MemoryKVStoreTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/storage/rocksdb/RocksKVStoreTest.java
Labels: cla:yes

#962 feat(iterator):Auto commit mode for applying log iterator
  jraft-core/src/main/java/com/alipay/sofa/jraft/Iterator.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/IteratorImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/IteratorWrapper.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/IteratorTest.java
Labels: cla:yes, size/M
