Repository sofastack/sofa-jraft, pull requests merged in 2023-03, with the labels that each got.

#935 auto publish to mvn central repo when create release
  .github/workflows/mvn_publish.yml
  jraft-core/pom.xml
  jraft-example/pom.xml
  jraft-extension/bdb-log-storage-impl/pom.xml
  jraft-extension/java-log-storage-impl/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: question, cla:yes, size/M

#936 maven-gpg-plugin loopback
  pom.xml
Labels: cla:yes, size/XS

#937 mvn deploy skipTest
  .github/workflows/mvn_publish.yml
  pom.xml
Labels: cla:yes, size/S

#938 rm mvn deploy way: on master push
  .github/workflows/mvn_publish.yml
Labels: cla:yes, size/XS

#933 Snapshot temporary directory support configurable
  jraft-core/src/main/java/com/alipay/sofa/jraft/JRaftServiceFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/DefaultJRaftServiceFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/core/NodeImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/NodeOptions.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/option/SnapshotExecutorOptions.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/SnapshotExecutorImpl.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotStorage.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/SnapshotExecutorTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/storage/snapshot/local/LocalSnapshotStorageTest.java
Labels: cla:yes, size/L
