Repository sofastack/sofa-jraft, pull requests merged in 2023-01, with the labels that each got.

#918 feat:propagate onerror event to statelistener
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/StateListener.java
  jraft-rheakv/rheakv-core/src/main/java/com/alipay/sofa/jraft/rhea/storage/KVStoreStateMachine.java
Labels: cla:yes, size/S

#923 update commet in SystemPropertyUtil
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/SystemPropertyUtil.java
Labels: cla:yes, size/XS

#892 fix(sec): upgrade com.fasterxml.jackson.core:jackson-databind to 2.12.6.1
  jraft-example/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
Labels: bug, size/XS, cla:no, First-time contributor

#929 upgrade jackson-format to 2.12.6
  jraft-example/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
Labels: cla:yes, size/XS

#927 (fix) 修复时间轮算法多循环低效率问题
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/timer/HashedWheelTimer.java
Labels: bug, cla:yes, First-time contributor, size/S
