Repository sofastack/sofa-jraft, pull requests merged in 2024-01, with the labels that each got.

#1058 chore: remove deprecated method to adapt higher rocksdb version
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/StorageOptionsFactory.java
  pom.xml
Labels: cla:yes, First-time contributor, size/S

#1066 修复loader.getResources无法读取资源的问题
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/JRaftServiceLoader.java
Labels: size/XS, cla:no, First-time contributor

#1068 add ping executor
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RaftRpcServerFactory.java
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/impl/PingRequestProcessor.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/ConnectionRefreshTest.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/rpc/impl/PingRequestProcessorTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/ConnectionRefreshTest.java
  jraft-extension/rpc-grpc-impl/src/test/java/com/alipay/sofa/jraft/rpc/impl/PingRequestProcessorTest.java
Labels: cla:yes, size/M

#1069 feat: release v1.3.14
  jraft-core/pom.xml
  jraft-core/src/main/java/com/alipay/sofa/jraft/rpc/RpcUtils.java
  jraft-example/pom.xml
  jraft-extension/bdb-log-storage-impl/pom.xml
  jraft-extension/java-log-storage-impl/pom.xml
  jraft-extension/pom.xml
  jraft-extension/rpc-grpc-impl/pom.xml
  jraft-rheakv/pom.xml
  jraft-rheakv/rheakv-core/pom.xml
  jraft-rheakv/rheakv-pd/pom.xml
  jraft-test/pom.xml
  pom.xml
Labels: cla:yes, size/M
