Repository sofastack/sofa-jraft, pull requests merged in 2024-06, with the labels that each got.

#1108 fix: ThreadId miss unlock(#1107)
  jraft-core/src/main/java/com/alipay/sofa/jraft/util/ThreadId.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/util/ThreadIdTest.java
Labels: bug, cla:yes, size/XS

#1110 fix: make chaosSplittingCheckData robust
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-extension/java-log-storage-impl/src/test/java/com/alipay/sofa/jraft/core/NodeTest.java
  jraft-rheakv/rheakv-core/src/test/java/com/alipay/sofa/jraft/rhea/chaos/AbstractChaosTest.java
Labels: bug, cla:yes, size/S

#1112 chore: remove redundant code
  jraft-core/src/test/java/com/alipay/sofa/jraft/core/BallotBoxTest.java
Labels: cla:yes, size/XS, First-time contributor

#1111 chore: add testToStringParseEmpty Test
  jraft-core/src/test/java/com/alipay/sofa/jraft/conf/ConfigurationTest.java
Labels: cla:yes, First-time contributor, size/S

#1113 chore: return false when peerId is blank
  jraft-core/src/main/java/com/alipay/sofa/jraft/entity/PeerId.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/entity/PeerIdTest.java
Labels: question, cla:yes, size/S

#1115 fix: trim peer str
  jraft-core/src/main/java/com/alipay/sofa/jraft/conf/Configuration.java
  jraft-core/src/test/java/com/alipay/sofa/jraft/conf/ConfigurationTest.java
Labels: bug, cla:yes, First-time contributor, size/S
